Draft: Feature/#33667 deadlines in xapi requests
integral-learning/moodle-mod_mumie pull request #58
Opened 2023-08-02 12:27 UTC by jtgoltz

2023-09-15 21:12 UTC, Lyannic requested changes
I did my best, but please keep in mind that I don't know anything about the plugin, Moodle and PHP.

2023-09-15 21:12 UTC, Lyannic commented on classes/grades/synchronization/xapi_request.php
> + * This class represents an xapi request used to retrieve grades for MUMIE Tasks,
Does the comma belong here?

2023-09-15 21:12 UTC, Lyannic commented on classes/grades/synchronization/xapi_request.php
> +        curl_setopt($ch, CURLOPT_USERAGENT, "My User Agent Name");
Do we really want to set this user agent?

2023-09-15 21:12 UTC, Lyannic commented on gradesync.php
> +     * Get an array of MUMIE users that have can submit answers to a given MUMIE Task.
Is this sentence really correct (`users that have can submit answers`)?

2023-09-15 21:12 UTC, Lyannic commented on classes/grades/synchronization/context/context_provider.php
> +     * Get context for a given list of mumie tasks and users.
Wrong capitalization. `MUMIE Tasks` is used everywhere else.

2023-10-16 15:30 UTC, fsacha commented on classes/grades/synchronization/context/context_provider.php
> +     * Get context for a given list of mumie tasks and users.
Renamed it.

2023-10-16 15:30 UTC, fsacha commented on classes/grades/synchronization/xapi_request.php
> +        curl_setopt($ch, CURLOPT_USERAGENT, "My User Agent Name");
I've renamed it to `Default User Name`. Let's discuss whether or not we should store data here in a separate story.

2023-10-16 15:30 UTC, fsacha commented on classes/grades/synchronization/context/object_context.php
> +class object_context implements \JsonSerializable {
This object is used for serialization. And because "LemonTree" shouldn't know anything about the "mumie", I would leave it at that. Dividing the object into one that is used as a model/"service" variable and one used for serialization would  exceed the scope of the story.

2023-10-16 15:30 UTC, fsacha commented on classes/grades/synchronization/context/context_provider.php
> + * This service is used to create the context that is required for some XAPI requests.
Renamed

2023-10-17 12:03 UTC, fsacha commented on classes/grades/synchronization/context/object_context.php
> +class object_context implements \JsonSerializable {
We will tackle this issue, when we refactor Moodle.

2023-10-17 12:07 UTC, dung238 commented on classes/grades/synchronization/xapi_request.php
> +        curl_setopt($ch, CURLOPT_USERAGENT, "My User Agent Name");
story created

2023-10-17 13:55 UTC, Lyannic commented on classes/grades/synchronization/context/object_context.php
> +class object_context implements \JsonSerializable {
A MUMIE Task is just a name for an activity in Moodle. Those activities can use problems/worksheets from LemonTree. This wouldn't make LemonTree know about the MUMIE at all. 
But I am in general fine with keeping it as is. I was just wondering, why it is called `object_context`.

2023-10-17 13:55 UTC, Lyannic commented on classes/grades/synchronization/xapi_request.php
> +        curl_setopt($ch, CURLOPT_USERAGENT, "My User Agent Name");
But is this new logic? Why do we need to send the user agent?

2023-10-18 09:19 UTC, fsacha commented on classes/grades/synchronization/xapi_request.php
> +        curl_setopt($ch, CURLOPT_USERAGENT, "My User Agent Name");
I remember Tobias saying something about it being necessary. I tested it again, and note synchronization works even without it. I removed it.

2023-10-19 14:28 UTC, fsacha commented on classes/grades/synchronization/context/object_context.php
> +class object_context implements \JsonSerializable {
I left it that way.

2023-10-19 14:28 UTC, merged